version: 1.0
runtime: python3
build:
  commands:
    build:
      - pip install -r requirements.txt
run:
  runtime-version: 3.11
  command: gunicorn --worker-class gthread --workers 4 --bind 0.0.0.0:8080 main:app
  network:
    port: 8080
  env:
    - name: PORT
      value: "8080"
services:
  - name: web
    git:
      branch: main
      repo_clone_url: ${_self}
    build_command: pip install -r requirements.txt
    run_command: gunicorn "main:app" --workers 4 --worker-class gthread --bind 0.0.0.0:8080 --log-level debug
    envs:
    - key: PORT
      value: "8080" 