version: 1.0
runtime: python3
build:
  commands:
    build:
      - pip install -r requirements.txt
run:
  runtime-version: 3.11
  command: gunicorn --worker-class gthread --workers 4 --bind 0.0.0.0:8080 main:app
  network:
    port: 8080
  env:
    - name: PORT
      value: "8080" 