name: quera-calendar-bot
services:
- name: bot
  github:
    branch: main
    deploy_on_push: true
    repo: your-username/your-repo
  build_command: pip install -r requirements.txt
  run_command: python main.py
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: BOT_TOKEN
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: BOT_USERNAME
    scope: RUN_AND_BUILD_TIME
    type: SECRET

runtime: python
env: flex

runtime_config:
  python_version: 3.11

manual_scaling:
  instances: 1

env_variables:
  PORT: "8080"

health_check:
  enable_health_check: true
  check_interval_sec: 10
  timeout_sec: 5
  unhealthy_threshold: 3
  healthy_threshold: 2
  restart_threshold: 300
  path: "/" 