runtime: python
env: flex
entrypoint: python main.py

runtime_config:
  python_version: 3.11

manual_scaling:
  instances: 1

env_variables:
  PORT: "8080"

health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
  restart_threshold: 300 